
(deluge:4514): GVFS-RemoteVolumeMonitor-WARNING **: Owner of volume monitor org.gtk.Private.MTPVolumeMonitor disconnected from the bus; removing drives/volumes/mounts

(deluge:4514): GVFS-RemoteVolumeMonitor-WARNING **: Owner of volume monitor org.gtk.Private.UDisks2VolumeMonitor disconnected from the bus; removing drives/volumes/mounts
g_dbus_connection_real_closed: Remote peer vanished with error: Erreur lors de la réception du message : Connexion ré-initialisée par le correspondant (g-io-error-quark, 0). Exiting.
Error creating proxy: Erreur lors de l'appel de StartServiceByName pour org.gtk.vfs.Daemon : La connexion est fermée (g-io-error-quark, 18)

(deluge:4514): GVFS-CRITICAL **: _g_daemon_vfs_get_mount_info_sync: assertion 'proxy != NULL' failed
Error creating proxy: Erreur lors de l'appel de StartServiceByName pour org.gtk.vfs.Daemon : La connexion est fermée (g-io-error-quark, 18)

(deluge:4514): GVFS-CRITICAL **: _g_daemon_vfs_get_mount_info_sync: assertion 'proxy != NULL' failed
Error creating proxy: Erreur lors de l'appel de StartServiceByName pour org.gtk.vfs.Daemon : La connexion est fermée (g-io-error-quark, 18)

(deluge:4514): GVFS-CRITICAL **: _g_daemon_vfs_get_mount_info_sync: assertion 'proxy != NULL' failed
Error creating proxy: Erreur lors de l'appel de StartServiceByName pour org.gtk.vfs.Daemon : La connexion est fermée (g-io-error-quark, 18)

(deluge:4514): GVFS-CRITICAL **: _g_daemon_vfs_get_mount_info_sync: assertion 'proxy != NULL' failed
Error creating proxy: Erreur lors de l'appel de StartServiceByName pour org.gtk.vfs.Daemon : La connexion est fermée (g-io-error-quark, 18)

(deluge:4514): GVFS-CRITICAL **: _g_daemon_vfs_get_mount_info_sync: assertion 'proxy != NULL' failed
Error creating proxy: Erreur lors de l'appel de StartServiceByName pour org.gtk.vfs.Daemon : La connexion est fermée (g-io-error-quark, 18)

(deluge:4514): GVFS-CRITICAL **: _g_daemon_vfs_get_mount_info_sync: assertion 'proxy != NULL' failed
deluge: Fatal IO error 0 (Succès) on X server :0.0.
